const FETCH_RANDOM_DOG_IMAGE_REQUESTED = 'FETCH_RANDOM_DOG_IMAGE_REQUESTED';
const FETCH_RANDOM_DOG_IMAGE_REQUESTED_CANCELLED = 'FETCH_RANDOM_DOG_IMAGE_REQUESTED_CANCELLED';
const FETCH_RANDOM_DOG_IMAGE_SUCCESS = 'FETCH_RANDOM_DOG_IMAGE_SUCCESS';
const FETCH_RANDOM_DOG_IMAGE_FAILURE = 'FETCH_RANDOM_DOG_IMAGE_FAILURE';

export default {
  FETCH_RANDOM_DOG_IMAGE_REQUESTED,
  FETCH_RANDOM_DOG_IMAGE_REQUESTED_CANCELLED,
  FETCH_RANDOM_DOG_IMAGE_SUCCESS,
  FETCH_RANDOM_DOG_IMAGE_FAILURE,
};
